### ISSUE TITLE
Make all messages configurable via a .yml file

### ISSUE THREAD

**Issue by Aaron2550** [leavessoft/EusUniBan#2]
This is so people can translate the messages into their server's main language or even use something like [https://www.spigotmc.org/resources/triton-translate-your-server.30331/](https://www.spigotmc.org/resources/triton-translate-your-server.30331/) easily

**Comment by richardhyy** [comment]
Thank you for your suggestion, and I'm working on this. ;)

**Comment by richardhyy** [comment]
Now most messages have been written in the config.yml, and will soon be moved to a separated file.

**Comment by Aaron2550** [comment]
Thanks! I didnt get a notification for some reason...
