### ISSUE TITLE
一点小建议qwq

### ISSUE THREAD

**Issue by ghost** [leavessoft/EusUniBan#3]
1. banlist.json可以格式化保存，这样直接打开文件查看会比较直观
2. 封禁信息包含封禁原因和封禁来源，便于管理员了解此玩家为什么被封禁

**Comment by richardhyy** [comment]
谢谢你的建议 ；）
已加入TODO-List。
关于2: 广播者将仍然可以设置不共享封禁原因，且来源仅在管理员查询时（/uniban check）可见。

**Comment by richardhyy** [comment]
封禁原因传递考虑到隐私问题，在想到其他妥协方案前暂时不会加入
